title: Alpine (s6-overlay) - Docker Image
description: Alpine (s6-overlay) Docker Image - Extends Official Alpine.
google_analytics: 
show_downloads: true

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]

theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
